
import './globals.css'
import { Inter } from 'next/font/google'
import ThemeProviderM from '@/components/ThemeProviderM'
import { NavbarMenu } from '@/components/NavbarMenu'
import Footer from '@/components/Footer'
import { SpeedDialCustomIcon } from '@/components/SpeedDialCustomIcon'
import LodingScreen from '@/components/LodingScreen'
const inter = Inter({ subsets: ['latin'] })
import { createClient } from 'contentful'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
/*

*/
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProviderM>
          <LodingScreen/>
          <NavbarMenu/>
          <SpeedDialCustomIcon/>
          {children}
          <Footer/>
        </ThemeProviderM>
      </body>
    </html>
  )
}

/*
export const  getStaticProps = async ({ params }) => {
  const client = contentful.createClient({
      space: "wqjm0ul81wfi",
      environment: 'master', // defaults to 'master' if not set
      accessToken: '1HOop-wSR5WmMg-bEn7Kythm5IZVtZijsDiW5qjAbFk'
  });

  const response = await client.getEntry(params.id);

  const product = {
    id: response.sys.id,
    name: response.fields.name,
    description: response.fields.description,
    image: response.fields.image.fields.file.url
  };

  return { props: { product }};
}
*/ 